//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationGreem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int id_Item { get; set; }
        public string Name { get; set; }
        public Nullable<int> Contract_id { get; set; }
    
        public virtual Contracts Contracts { get; set; }
    }
}
